export const IS_ERROR = 'IS_ERROR';
export const PEOPLE_LOAD = 'PEOPLE_LOAD';
export const PEOPLE_LOAD_FULFILLED = 'PEOPLE_LOAD_FULFILLED';
export const PEOPLE_LOAD_REJECTED = 'PEOPLE_LOAD_REJECTED';
